
    <section id="calendar" class="content-section">
        <div class="card card-elevated">
            <div class="card-header">
                <div>
                    <h3 class="card-title">Calendar - Klub Basket</h3>
                    <p class="card-subtitle">
                        Kelola jadwal kegiatan dengan kalender interaktif
                    </p>
                </div>
                <div class="card-actions">
                    <button class="btn btn-secondary btn-sm" onclick="exportSchedule()">
                        📊 Export Jadwal
                    </button>
                    <button class="btn btn-primary" onclick="openModal('scheduleModal')">
                        ➕ Tambah Jadwal
                    </button>
                </div>
            </div>

            <!-- Enhanced Calendar -->
            <div class="calendar-container">
                <div class="calendar-header">
                    <h4 class="calendar-title" id="currentMonth">Maret 2025</h4>
                    <div class="calendar-nav">
                        <button class="calendar-nav-btn" onclick="previousMonth()" aria-label="Previous Month">
                            ‹
                        </button>
                        <button class="calendar-nav-btn" onclick="goToToday()">
                            Hari Ini
                        </button>
                        <button class="calendar-nav-btn" onclick="nextMonth()" aria-label="Next Month">
                            ›
                        </button>
                    </div>
                </div>

                <div class="calendar-grid">
                    <!-- Day Headers -->
                    <div class="calendar-day-header">Min</div>
                    <div class="calendar-day-header">Sen</div>
                    <div class="calendar-day-header">Sel</div>
                    <div class="calendar-day-header">Rab</div>
                    <div class="calendar-day-header">Kam</div>
                    <div class="calendar-day-header">Jum</div>
                    <div class="calendar-day-header">Sab</div>

                    <!-- Calendar Days will be generated by JavaScript -->
                    <div id="calendarDays" style="grid-column: 1 / -1; display: contents">
                        <!-- Days will be dynamically inserted here -->
                    </div>
                </div>
            </div>

            <!-- Schedule Legend -->
            <div
                style="
                  display: flex;
                  gap: var(--space-4);
                  margin: var(--space-6) 0;
                  flex-wrap: wrap;
                  justify-content: center;
                ">
                <div
                    style="
                    display: flex;
                    align-items: center;
                    gap: var(--space-2);
                  ">
                    <div
                        style="
                      width: 16px;
                      height: 16px;
                      background: linear-gradient(
                        135deg,
                        var(--primary-500),
                        var(--primary-600)
                      );
                      border-radius: 50%;
                    ">
                    </div>
                    <span style="font-size: var(--font-size-sm)">Hari Ini</span>
                </div>
                <div
                    style="
                    display: flex;
                    align-items: center;
                    gap: var(--space-2);
                  ">
                    <div
                        style="
                      width: 16px;
                      height: 16px;
                      background: linear-gradient(
                        135deg,
                        var(--error-500),
                        var(--error-600)
                      );
                      border-radius: 50%;
                    ">
                    </div>
                    <span style="font-size: var(--font-size-sm)">Ada Jadwal</span>
                </div>
                <div
                    style="
                    display: flex;
                    align-items: center;
                    gap: var(--space-2);
                  ">
                    <div
                        style="
                      width: 16px;
                      height: 16px;
                      background: linear-gradient(
                        135deg,
                        var(--accent-500),
                        var(--accent-600)
                      );
                      border-radius: 50%;
                    ">
                    </div>
                    <span style="font-size: var(--font-size-sm)">Dipilih</span>
                </div>
            </div>

            <!-- Selected Date Schedule -->
            <div id="selectedDateSchedule" style="margin-top: var(--space-8)">
                <h4
                    style="
                    font-size: var(--font-size-xl);
                    font-weight: var(--font-weight-bold);
                    margin-bottom: var(--space-6);
                    color: var(--text-primary);
                  ">
                    📅 Jadwal Hari Ini - Senin, 15 Maret 2025
                </h4>

                <div class="schedule-cards">
                    <div class="schedule-card">
                        <div class="schedule-time">15:30 - 17:00</div>
                        <div class="schedule-activity">Latihan Basket Reguler</div>
                        <div class="schedule-location">
                            📍 Lapangan Basket Utama
                        </div>
                        <div class="schedule-participants">
                            👥 85 siswa terdaftar • 78 hadir
                        </div>
                        <div class="schedule-actions">
                            <button class="btn btn-ghost btn-sm" onclick="editSchedule(1)">
                                ✏️
                            </button>
                            <button class="btn btn-ghost btn-sm" onclick="takeAttendance(1)">
                                ✅ Absen
                            </button>
                            <button class="btn btn-ghost btn-sm" onclick="viewScheduleDetails(1)">
                                👁️
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Weekly Overview -->
            <div style="margin-top: var(--space-8)">
                <h4
                    style="
                    font-size: var(--font-size-xl);
                    font-weight: var(--font-weight-bold);
                    margin-bottom: var(--space-6);
                    color: var(--text-primary);
                  ">
                    📊 Ringkasan Minggu Ini
                </h4>

                <div class="stats-grid"
                    style="
                    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                    gap: var(--space-4);
                  ">
                    <div class="stat-card" style="padding: var(--space-4)">
                        <div class="stat-number" style="font-size: var(--font-size-2xl)">
                            6
                        </div>
                        <div class="stat-label">Total Jadwal</div>
                    </div>
                    <div class="stat-card success" style="padding: var(--space-4)">
                        <div class="stat-number" style="font-size: var(--font-size-2xl)">
                            5
                        </div>
                        <div class="stat-label">Terlaksana</div>
                    </div>
                    <div class="stat-card warning" style="padding: var(--space-4)">
                        <div class="stat-number" style="font-size: var(--font-size-2xl)">
                            1
                        </div>
                        <div class="stat-label">Akan Datang</div>
                    </div>
                    <div class="stat-card error" style="padding: var(--space-4)">
                        <div class="stat-number" style="font-size: var(--font-size-2xl)">
                            0
                        </div>
                        <div class="stat-label">Dibatalkan</div>
                    </div>
                </div>
            </div>
        </div>
    </section>