<!DOCTYPE html>
<html lang="id">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
    <title>EkstraKu Admin - Enhanced Dashboard Management</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap"
        rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@3"></script>
    <link rel="stylesheet" href="{{ asset('styles/admin.css') }}">
</head>

<body>
    <div class="admin-layout">
        @include('admin.layouts.sidebar')
        <main class="main-content">
            @include('admin.layouts.header')

            <div class="content">
                @yield('content')
            </div>
        </main>
    </div>
    <script>

        // ===== ENHANCED SAMPLE DATA =====
        const sampleData = {
            activities:  @json($ekstra) ,
            students: [{
                    id: 1,
                    nama: "Ahmad Rizki Pratama",
                    email: "ahmad.rizki@student.edu",
                    kelas: "11",
                    kegiatan: "Klub Basket",
                    status: "aktif",
                    jenisKelamin: "L",
                    tanggalLahir: "2007-05-15",
                    alamat: "Jl. Merdeka No. 123, Jakarta",
                    performance: 85,
                },
                {
                    id: 2,
                    nama: "Siti Nurhaliza Putri",
                    email: "siti.nur@student.edu",
                    kelas: "10",
                    kegiatan: "Komunitas Drama",
                    status: "aktif",
                    jenisKelamin: "P",
                    tanggalLahir: "2008-03-22",
                    alamat: "Jl. Sudirman No. 456, Jakarta",
                    performance: 92,
                },
                {
                    id: 3,
                    nama: "Budi Santoso",
                    email: "budi.santoso@student.edu",
                    kelas: "12",
                    kegiatan: "Olimpiade Sains",
                    status: "aktif",
                    jenisKelamin: "L",
                    tanggalLahir: "2006-11-08",
                    alamat: "Jl. Thamrin No. 789, Jakarta",
                    performance: 98,
                },
                {
                    id: 4,
                    nama: "Maya Sari Dewi",
                    email: "maya.sari@student.edu",
                    kelas: "11",
                    kegiatan: "Klub Fotografi",
                    status: "aktif",
                    jenisKelamin: "P",
                    tanggalLahir: "2007-07-12",
                    alamat: "Jl. Gatot Subroto No. 321, Jakarta",
                    performance: 88,
                },
                {
                    id: 5,
                    nama: "Andi Pratama",
                    email: "andi.pratama@student.edu",
                    kelas: "10",
                    kegiatan: "Tim Debat",
                    status: "aktif",
                    jenisKelamin: "L",
                    tanggalLahir: "2008-01-30",
                    alamat: "Jl. Kuningan No. 654, Jakarta",
                    performance: 90,
                },
                {
                    id: 6,
                    nama: "Dewi Lestari",
                    email: "dewi.lestari@student.edu",
                    kelas: "12",
                    kegiatan: "Band Musik",
                    status: "aktif",
                    jenisKelamin: "P",
                    tanggalLahir: "2006-09-18",
                    alamat: "Jl. Senayan No. 987, Jakarta",
                    performance: 87,
                },
                {
                    id: 7,
                    nama: "Rudi Hermawan",
                    email: "rudi.hermawan@student.edu",
                    kelas: "11",
                    kegiatan: "Klub Robotika",
                    status: "aktif",
                    jenisKelamin: "L",
                    tanggalLahir: "2007-04-25",
                    alamat: "Jl. Kemang No. 147, Jakarta",
                    performance: 94,
                },
                {
                    id: 8,
                    nama: "Indah Permata Sari",
                    email: "indah.permata@student.edu",
                    kelas: "10",
                    kegiatan: "Paduan Suara",
                    status: "aktif",
                    jenisKelamin: "P",
                    tanggalLahir: "2008-06-14",
                    alamat: "Jl. Menteng No. 258, Jakarta",
                    performance: 89,
                },
                {
                    id: 9,
                    nama: "Fajar Nugroho",
                    email: "fajar.nugroho@student.edu",
                    kelas: "12",
                    kegiatan: "Klub Sastra",
                    status: "aktif",
                    jenisKelamin: "L",
                    tanggalLahir: "2006-12-03",
                    alamat: "Jl. Cikini No. 369, Jakarta",
                    performance: 86,
                },
                {
                    id: 10,
                    nama: "Rina Wulandari",
                    email: "rina.wulandari@student.edu",
                    kelas: "11",
                    kegiatan: "Tim Futsal",
                    status: "aktif",
                    jenisKelamin: "P",
                    tanggalLahir: "2007-08-27",
                    alamat: "Jl. Tebet No. 741, Jakarta",
                    performance: 83,
                },
                {
                    id: 11,
                    nama: "Dimas Prasetyo",
                    email: "dimas.prasetyo@student.edu",
                    kelas: "10",
                    kegiatan: "Klub Lingkungan",
                    status: "aktif",
                    jenisKelamin: "L",
                    tanggalLahir: "2008-02-11",
                    alamat: "Jl. Pancoran No. 852, Jakarta",
                    performance: 91,
                },
                {
                    id: 12,
                    nama: "Ayu Kartika",
                    email: "ayu.kartika@student.edu",
                    kelas: "12",
                    kegiatan: "Klub Bahasa Inggris",
                    status: "aktif",
                    jenisKelamin: "P",
                    tanggalLahir: "2006-10-19",
                    alamat: "Jl. Pasar Minggu No. 963, Jakarta",
                    performance: 88,
                },
                {
                    id: 13,
                    nama: "Rizky Ramadhan",
                    email: "rizky.ramadhan@student.edu",
                    kelas: "11",
                    kegiatan: "Klub Matematika",
                    status: "aktif",
                    jenisKelamin: "L",
                    tanggalLahir: "2007-03-07",
                    alamat: "Jl. Kalibata No. 159, Jakarta",
                    performance: 95,
                },
                {
                    id: 14,
                    nama: "Sari Melati",
                    email: "sari.melati@student.edu",
                    kelas: "10",
                    kegiatan: "Klub Tari Tradisional",
                    status: "aktif",
                    jenisKelamin: "P",
                    tanggalLahir: "2008-05-23",
                    alamat: "Jl. Mampang No. 357, Jakarta",
                    performance: 87,
                },
                {
                    id: 15,
                    nama: "Bayu Setiawan",
                    email: "bayu.setiawan@student.edu",
                    kelas: "12",
                    kegiatan: "Klub Jurnalistik",
                    status: "aktif",
                    jenisKelamin: "L",
                    tanggalLahir: "2006-07-16",
                    alamat: "Jl. Warung Buncit No. 468, Jakarta",
                    performance: 84,
                },
                {
                    id: 16,
                    nama: "Lina Marlina",
                    email: "lina.marlina@student.edu",
                    kelas: "11",
                    kegiatan: "Klub Voli",
                    status: "aktif",
                    jenisKelamin: "P",
                    tanggalLahir: "2007-09-04",
                    alamat: "Jl. Cilandak No. 579, Jakarta",
                    performance: 86,
                },
                {
                    id: 17,
                    nama: "Hendra Wijaya",
                    email: "hendra.wijaya@student.edu",
                    kelas: "10",
                    kegiatan: "Klub Catur",
                    status: "aktif",
                    jenisKelamin: "L",
                    tanggalLahir: "2008-11-28",
                    alamat: "Jl. Lebak Bulus No. 681, Jakarta",
                    performance: 92,
                },
                {
                    id: 18,
                    nama: "Putri Anggraini",
                    email: "putri.anggraini@student.edu",
                    kelas: "12",
                    kegiatan: "Klub Memasak",
                    status: "aktif",
                    jenisKelamin: "P",
                    tanggalLahir: "2006-04-13",
                    alamat: "Jl. Pondok Indah No. 792, Jakarta",
                    performance: 89,
                },
                {
                    id: 19,
                    nama: "Arif Budiman",
                    email: "arif.budiman@student.edu",
                    kelas: "11",
                    kegiatan: "Klub Badminton",
                    status: "aktif",
                    jenisKelamin: "L",
                    tanggalLahir: "2007-06-21",
                    alamat: "Jl. Kemang Raya No. 813, Jakarta",
                    performance: 85,
                },
                {
                    id: 20,
                    nama: "Nisa Rahmawati",
                    email: "nisa.rahmawati@student.edu",
                    kelas: "10",
                    kegiatan: "Klub Desain Grafis",
                    status: "aktif",
                    jenisKelamin: "P",
                    tanggalLahir: "2008-08-09",
                    alamat: "Jl. Radio Dalam No. 924, Jakarta",
                    performance: 90,
                },
                {
                    id: 21,
                    nama: "Ilham",
                    email: "ilham.bejir@student.edu",
                    kelas: "10",
                    kegiatan: "Klub Desain Grafis",
                    status: "aktif",
                    jenisKelamin: "L",
                    tanggalLahir: "2008-08-09",
                    alamat: "Jl. Radio Dalam No. 924, Jakarta",
                    performance: 90,
                },
            ],
            registrations: [{
                    id: 1,
                    siswa: "Ahmad Rizki Pratama",
                    kegiatan: "Klub Basket",
                    tanggal: "2024-03-10",
                    status: "pending",
                    email: "ahmad.rizki@student.edu",
                    kelas: "11",
                    urgency: "normal",
                },
                {
                    id: 2,
                    siswa: "Siti Nurhaliza Putri",
                    kegiatan: "Komunitas Drama",
                    tanggal: "2024-03-11",
                    status: "approved",
                    email: "siti.nur@student.edu",
                    kelas: "10",
                    urgency: "normal",
                },
                {
                    id: 3,
                    siswa: "Budi Santoso",
                    kegiatan: "Olimpiade Sains",
                    tanggal: "2024-03-12",
                    status: "pending",
                    email: "budi.santoso@student.edu",
                    kelas: "12",
                    urgency: "high",
                },
                {
                    id: 4,
                    siswa: "Maya Sari Dewi",
                    kegiatan: "Klub Fotografi",
                    tanggal: "2024-03-13",
                    status: "approved",
                    email: "maya.sari@student.edu",
                    kelas: "11",
                    urgency: "normal",
                },
                {
                    id: 5,
                    siswa: "Andi Pratama",
                    kegiatan: "Tim Debat",
                    tanggal: "2024-03-14",
                    status: "rejected",
                    email: "andi.pratama@student.edu",
                    kelas: "10",
                    urgency: "low",
                },
                {
                    id: 6,
                    siswa: "Dewi Lestari",
                    kegiatan: "Band Musik",
                    tanggal: "2024-03-15",
                    status: "pending",
                    email: "dewi.lestari@student.edu",
                    kelas: "12",
                    urgency: "high",
                },
                {
                    id: 7,
                    siswa: "Rudi Hermawan",
                    kegiatan: "Klub Robotika",
                    tanggal: "2024-03-16",
                    status: "approved",
                    email: "rudi.hermawan@student.edu",
                    kelas: "11",
                    urgency: "normal",
                },
                {
                    id: 8,
                    siswa: "Indah Permata Sari",
                    kegiatan: "Paduan Suara",
                    tanggal: "2024-03-17",
                    status: "pending",
                    email: "indah.permata@student.edu",
                    kelas: "10",
                    urgency: "normal",
                },
                {
                    id: 9,
                    siswa: "Fajar Nugroho",
                    kegiatan: "Klub Sastra",
                    tanggal: "2024-03-18",
                    status: "approved",
                    email: "fajar.nugroho@student.edu",
                    kelas: "12",
                    urgency: "low",
                },
                {
                    id: 10,
                    siswa: "Rina Wulandari",
                    kegiatan: "Tim Futsal",
                    tanggal: "2024-03-19",
                    status: "pending",
                    email: "rina.wulandari@student.edu",
                    kelas: "11",
                    urgency: "high",
                },
                {
                    id: 11,
                    siswa: "Dimas Prasetyo",
                    kegiatan: "Klub Lingkungan",
                    tanggal: "2024-03-20",
                    status: "approved",
                    email: "dimas.prasetyo@student.edu",
                    kelas: "10",
                    urgency: "normal",
                },
                {
                    id: 12,
                    siswa: "Ayu Kartika",
                    kegiatan: "Klub Bahasa Inggris",
                    tanggal: "2024-03-21",
                    status: "pending",
                    email: "ayu.kartika@student.edu",
                    kelas: "12",
                    urgency: "normal",
                },
                {
                    id: 13,
                    siswa: "Rizky Ramadhan",
                    kegiatan: "Klub Matematika",
                    tanggal: "2024-03-22",
                    status: "rejected",
                    email: "rizky.ramadhan@student.edu",
                    kelas: "11",
                    urgency: "low",
                },
                {
                    id: 14,
                    siswa: "Sari Melati",
                    kegiatan: "Klub Tari Tradisional",
                    tanggal: "2024-03-23",
                    status: "approved",
                    email: "sari.melati@student.edu",
                    kelas: "10",
                    urgency: "normal",
                },
                {
                    id: 15,
                    siswa: "Bayu Setiawan",
                    kegiatan: "Klub Jurnalistik",
                    tanggal: "2024-03-24",
                    status: "pending",
                    email: "bayu.setiawan@student.edu",
                    kelas: "12",
                    urgency: "high",
                },
            ],
            announcements: [{
                    id: 1,
                    judul: "Pendaftaran Turnamen Basket Dibuka",
                    kegiatan: "Klub Basket",
                    tanggal: "2024-03-01",
                    status: "aktif",
                    prioritas: "tinggi",
                    isi: "Turnamen basket antar sekolah akan segera dimulai. Pendaftaran dibuka untuk semua anggota klub basket. Hadiah menarik menanti para juara!",
                    views: 245,
                    likes: 89,
                },
                {
                    id: 2,
                    judul: "Pertunjukan Drama Musim Semi",
                    kegiatan: "Komunitas Drama",
                    tanggal: "2024-03-05",
                    status: "aktif",
                    prioritas: "normal",
                    isi: "Komunitas drama akan mengadakan pertunjukan spesial musim semi. Tiket sudah tersedia di sekretariat. Jangan sampai terlewat!",
                    views: 178,
                    likes: 65,
                },
                {
                    id: 3,
                    judul: "Workshop Pameran Sains",
                    kegiatan: "Olimpiade Sains",
                    tanggal: "2024-03-08",
                    status: "aktif",
                    prioritas: "tinggi",
                    isi: "Workshop persiapan olimpiade sains tingkat nasional akan diadakan akhir bulan ini. Materi berkualitas dari mentor berpengalaman.",
                    views: 198,
                    likes: 72,
                },
                {
                    id: 4,
                    judul: "Pameran Fotografi Tahunan",
                    kegiatan: "Klub Fotografi",
                    tanggal: "2024-03-10",
                    status: "aktif",
                    prioritas: "normal",
                    isi: "Pameran foto karya siswa akan dipamerkan di galeri sekolah selama sebulan penuh. Tema tahun ini adalah 'Keindahan Alam Indonesia'.",
                    views: 156,
                    likes: 48,
                },
                {
                    id: 5,
                    judul: "Kompetisi Debat Antar Sekolah",
                    kegiatan: "Tim Debat",
                    tanggal: "2024-03-12",
                    status: "draft",
                    prioritas: "urgent",
                    isi: "Tim debat sekolah akan mengikuti kompetisi tingkat provinsi bulan depan. Persiapan intensif akan dimulai minggu depan.",
                    views: 0,
                    likes: 0,
                },
                {
                    id: 6,
                    judul: "Konser Musik Sekolah",
                    kegiatan: "Band Musik",
                    tanggal: "2024-03-15",
                    status: "aktif",
                    prioritas: "normal",
                    isi: "Band musik sekolah akan mengadakan konser amal untuk membantu korban bencana alam. Mari bersama-sama berbagi kebahagiaan.",
                    views: 289,
                    likes: 134,
                },
                {
                    id: 7,
                    judul: "Lomba Robot Tingkat Nasional",
                    kegiatan: "Klub Robotika",
                    tanggal: "2024-03-18",
                    status: "aktif",
                    prioritas: "tinggi",
                    isi: "Klub robotika berhasil lolos ke tingkat nasional dan akan bertanding bulan depan. Dukungan kalian sangat berarti!",
                    views: 167,
                    likes: 78,
                },
                {
                    id: 8,
                    judul: "Festival Paduan Suara",
                    kegiatan: "Paduan Suara",
                    tanggal: "2024-03-20",
                    status: "draft",
                    prioritas: "normal",
                    isi: "Paduan suara akan mengikuti festival musik daerah yang diadakan di gedung kesenian. Latihan tambahan akan diadakan.",
                    views: 0,
                    likes: 0,
                },
                {
                    id: 9,
                    judul: "Peluncuran Majalah Sekolah",
                    kegiatan: "Klub Jurnalistik",
                    tanggal: "2024-03-22",
                    status: "aktif",
                    prioritas: "normal",
                    isi: "Majalah sekolah edisi terbaru telah terbit dengan tema 'Masa Depan Pendidikan'. Dapatkan di perpustakaan sekolah.",
                    views: 134,
                    likes: 56,
                },
                {
                    id: 10,
                    judul: "Pelatihan Kepemimpinan",
                    kegiatan: "Umum",
                    tanggal: "2024-03-25",
                    status: "aktif",
                    prioritas: "tinggi",
                    isi: "Pelatihan kepemimpinan untuk pengurus OSIS dan ketua ekstrakurikuler akan diadakan akhir bulan. Pendaftaran terbatas!",
                    views: 298,
                    likes: 145,
                },
            ],
            mentors: [{
                    id: 1,
                    nama: "Pelatih Johnson",
                    email: "johnson@school.edu",
                    kegiatan: "Klub Basket",
                    pengalaman: "8 tahun",
                    status: "aktif",
                    keahlian: "olahraga",
                    telepon: "+62 812 3456 7890",
                    rating: 4.9,
                    achievements: 12,
                },
                {
                    id: 2,
                    nama: "Ibu Anderson",
                    email: "anderson@school.edu",
                    kegiatan: "Komunitas Drama",
                    pengalaman: "12 tahun",
                    status: "aktif",
                    keahlian: "seni",
                    telepon: "+62 813 4567 8901",
                    rating: 4.8,
                    achievements: 15,
                },
                {
                    id: 3,
                    nama: "Dr. Smith",
                    email: "smith@school.edu",
                    kegiatan: "Olimpiade Sains",
                    pengalaman: "15 tahun",
                    status: "aktif",
                    keahlian: "akademik",
                    telepon: "+62 814 5678 9012",
                    rating: 4.9,
                    achievements: 25,
                },
                {
                    id: 4,
                    nama: "Pak Wilson",
                    email: "wilson@school.edu",
                    kegiatan: "Klub Fotografi",
                    pengalaman: "6 tahun",
                    status: "aktif",
                    keahlian: "seni",
                    telepon: "+62 815 6789 0123",
                    rating: 4.7,
                    achievements: 8,
                },
                {
                    id: 5,
                    nama: "Ibu Davis",
                    email: "davis@school.edu",
                    kegiatan: "Tim Debat",
                    pengalaman: "10 tahun",
                    status: "aktif",
                    keahlian: "akademik",
                    telepon: "+62 816 7890 1234",
                    rating: 4.8,
                    achievements: 18,
                },
                {
                    id: 6,
                    nama: "Pak Brown",
                    email: "brown@school.edu",
                    kegiatan: "Band Musik",
                    pengalaman: "14 tahun",
                    status: "aktif",
                    keahlian: "seni",
                    telepon: "+62 817 8901 2345",
                    rating: 4.9,
                    achievements: 22,
                },
                {
                    id: 7,
                    nama: "Dr. Tech",
                    email: "tech@school.edu",
                    kegiatan: "Klub Robotika",
                    pengalaman: "9 tahun",
                    status: "aktif",
                    keahlian: "teknologi",
                    telepon: "+62 818 9012 3456",
                    rating: 4.8,
                    achievements: 16,
                },
                {
                    id: 8,
                    nama: "Ibu Melody",
                    email: "melody@school.edu",
                    kegiatan: "Paduan Suara",
                    pengalaman: "11 tahun",
                    status: "aktif",
                    keahlian: "seni",
                    telepon: "+62 819 0123 4567",
                    rating: 4.7,
                    achievements: 13,
                },
                {
                    id: 9,
                    nama: "Pak Penulis",
                    email: "penulis@school.edu",
                    kegiatan: "Klub Sastra",
                    pengalaman: "13 tahun",
                    status: "aktif",
                    keahlian: "akademik",
                    telepon: "+62 820 1234 5678",
                    rating: 4.6,
                    achievements: 11,
                },
                {
                    id: 10,
                    nama: "Pelatih Bola",
                    email: "bola@school.edu",
                    kegiatan: "Tim Futsal",
                    pengalaman: "7 tahun",
                    status: "aktif",
                    keahlian: "olahraga",
                    telepon: "+62 821 2345 6789",
                    rating: 4.8,
                    achievements: 14,
                },
            ],
            users: [{
                    id: 1,
                    username: "admin",
                    email: "admin@ekstraku.edu",
                    role: "Admin",
                    lastLogin: "2024-03-15 10:30",
                    status: "aktif",
                    loginCount: 1245,
                    permissions: ["all"],
                },
                {
                    id: 2,
                    username: "johnson",
                    email: "johnson@school.edu",
                    role: "Mentor",
                    lastLogin: "2024-03-15 09:15",
                    status: "aktif",
                    loginCount: 523,
                    permissions: ["activities", "students"],
                },
                {
                    id: 3,
                    username: "ahmad.rizki",
                    email: "ahmad.rizki@student.edu",
                    role: "Siswa",
                    lastLogin: "2024-03-15 08:45",
                    status: "aktif",
                    loginCount: 189,
                    permissions: ["profile"],
                },
                {
                    id: 4,
                    username: "anderson",
                    email: "anderson@school.edu",
                    role: "Mentor",
                    lastLogin: "2024-03-14 16:20",
                    status: "aktif",
                    loginCount: 678,
                    permissions: ["activities", "students"],
                },
                {
                    id: 5,
                    username: "siti.nur",
                    email: "siti.nur@student.edu",
                    role: "Siswa",
                    lastLogin: "2024-03-14 14:30",
                    status: "aktif",
                    loginCount: 156,
                    permissions: ["profile"],
                },
                {
                    id: 6,
                    username: "dr.smith",
                    email: "smith@school.edu",
                    role: "Mentor",
                    lastLogin: "2024-03-14 11:45",
                    status: "aktif",
                    loginCount: 789,
                    permissions: ["activities", "students"],
                },
                {
                    id: 7,
                    username: "budi.santoso",
                    email: "budi.santoso@student.edu",
                    role: "Siswa",
                    lastLogin: "2024-03-13 15:20",
                    status: "aktif",
                    loginCount: 234,
                    permissions: ["profile"],
                },
                {
                    id: 8,
                    username: "wilson",
                    email: "wilson@school.edu",
                    role: "Mentor",
                    lastLogin: "2024-03-13 13:10",
                    status: "aktif",
                    loginCount: 456,
                    permissions: ["activities", "students"],
                },
                {
                    id: 9,
                    username: "maya.sari",
                    email: "maya.sari@student.edu",
                    role: "Siswa",
                    lastLogin: "2024-03-13 09:30",
                    status: "aktif",
                    loginCount: 167,
                    permissions: ["profile"],
                },
                {
                    id: 10,
                    username: "davis",
                    email: "davis@school.edu",
                    role: "Mentor",
                    lastLogin: "2024-03-12 17:45",
                    status: "aktif",
                    loginCount: 612,
                    permissions: ["activities", "students"],
                },
            ],
            activities_recent: [{
                    icon: "👥",
                    title: "Siswa baru mendaftar",
                    description: "Ahmad Rizki mendaftar ke Klub Basket",
                    time: "10 menit yang lalu",
                    type: "success",
                    category: "registration",
                },
                {
                    icon: "📢",
                    title: "Pengumuman dipublikasi",
                    description: "Pengumuman turnamen basket telah dipublikasi",
                    time: "30 menit yang lalu",
                    type: "info",
                    category: "announcement",
                },
                {
                    icon: "✅",
                    title: "Pendaftaran disetujui",
                    description: "5 pendaftaran baru telah disetujui",
                    time: "1 jam yang lalu",
                    type: "success",
                    category: "approval",
                },
                {
                    icon: "👨‍🏫",
                    title: "Mentor baru ditambahkan",
                    description: "Dr. Tech bergabung sebagai pembina robotika",
                    time: "2 jam yang lalu",
                    type: "warning",
                    category: "mentor",
                },
                {
                    icon: "📊",
                    title: "Laporan bulanan",
                    description: "Laporan partisipasi bulan Maret telah dibuat",
                    time: "3 jam yang lalu",
                    type: "info",
                    category: "report",
                },
                {
                    icon: "🎯",
                    title: "Kegiatan diperbarui",
                    description: "Jadwal Komunitas Drama telah diperbarui",
                    time: "4 jam yang lalu",
                    type: "warning",
                    category: "update",
                },
                {
                    icon: "🔔",
                    title: "Notifikasi sistem",
                    description: "Backup data berhasil dilakukan",
                    time: "5 jam yang lalu",
                    type: "success",
                    category: "system",
                },
                {
                    icon: "📝",
                    title: "Pendaftaran baru",
                    description: "Siti Nurhaliza mendaftar ke Komunitas Drama",
                    time: "6 jam yang lalu",
                    type: "info",
                    category: "registration",
                },
                {
                    icon: "🏆",
                    title: "Prestasi baru",
                    description: "Tim Debat meraih juara 1 tingkat kota",
                    time: "1 hari yang lalu",
                    type: "success",
                    category: "achievement",
                },
                {
                    icon: "📅",
                    title: "Jadwal diperbarui",
                    description: "Jadwal latihan Band Musik diubah",
                    time: "1 hari yang lalu",
                    type: "warning",
                    category: "schedule",
                },
            ],
        };
        console.log(sampleData)
    </script>

    <script src="{{ asset('scripts/admin.js') }}"></script>
</body>

</html>
