<!DOCTYPE html>
<html lang="id">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
    <title>EkstraKu Admin</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap"
        rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@3"></script>
    <link rel="stylesheet" href="{{ asset('styles/admin.css') }}">
</head>

<body>
    <div class="admin-layout">
        @include('admin.layouts.sidebar')
        <main class="main-content">
            @include('admin.layouts.header')

            <div class="content">
                @yield('content')
            </div>
        </main>
    </div>
    <script>

        // ===== ENHANCED SAMPLE DATA =====
        const sampleData = {
            activities:  @json($ekstra) ,
            students: @json($siswa),
            registrations: [{
                    id: 1,
                    siswa: "Ahmad Rizki Pratama",
                    kegiatan: "Klub Basket",
                    tanggal: "2024-03-10",
                    status: "pending",
                    email: "ahmad.rizki@student.edu",
                    kelas: "11",
                    urgency: "normal",
                },
                {
                    id: 2,
                    siswa: "Siti Nurhaliza Putri",
                    kegiatan: "Komunitas Drama",
                    tanggal: "2024-03-11",
                    status: "approved",
                    email: "siti.nur@student.edu",
                    kelas: "10",
                    urgency: "normal",
                },
                {
                    id: 3,
                    siswa: "Budi Santoso",
                    kegiatan: "Olimpiade Sains",
                    tanggal: "2024-03-12",
                    status: "pending",
                    email: "budi.santoso@student.edu",
                    kelas: "12",
                    urgency: "high",
                },
                {
                    id: 4,
                    siswa: "Maya Sari Dewi",
                    kegiatan: "Klub Fotografi",
                    tanggal: "2024-03-13",
                    status: "approved",
                    email: "maya.sari@student.edu",
                    kelas: "11",
                    urgency: "normal",
                },
                {
                    id: 5,
                    siswa: "Andi Pratama",
                    kegiatan: "Tim Debat",
                    tanggal: "2024-03-14",
                    status: "rejected",
                    email: "andi.pratama@student.edu",
                    kelas: "10",
                    urgency: "low",
                },
                {
                    id: 6,
                    siswa: "Dewi Lestari",
                    kegiatan: "Band Musik",
                    tanggal: "2024-03-15",
                    status: "pending",
                    email: "dewi.lestari@student.edu",
                    kelas: "12",
                    urgency: "high",
                },
                {
                    id: 7,
                    siswa: "Rudi Hermawan",
                    kegiatan: "Klub Robotika",
                    tanggal: "2024-03-16",
                    status: "approved",
                    email: "rudi.hermawan@student.edu",
                    kelas: "11",
                    urgency: "normal",
                },
                {
                    id: 8,
                    siswa: "Indah Permata Sari",
                    kegiatan: "Paduan Suara",
                    tanggal: "2024-03-17",
                    status: "pending",
                    email: "indah.permata@student.edu",
                    kelas: "10",
                    urgency: "normal",
                },
                {
                    id: 9,
                    siswa: "Fajar Nugroho",
                    kegiatan: "Klub Sastra",
                    tanggal: "2024-03-18",
                    status: "approved",
                    email: "fajar.nugroho@student.edu",
                    kelas: "12",
                    urgency: "low",
                },
                {
                    id: 10,
                    siswa: "Rina Wulandari",
                    kegiatan: "Tim Futsal",
                    tanggal: "2024-03-19",
                    status: "pending",
                    email: "rina.wulandari@student.edu",
                    kelas: "11",
                    urgency: "high",
                },
                {
                    id: 11,
                    siswa: "Dimas Prasetyo",
                    kegiatan: "Klub Lingkungan",
                    tanggal: "2024-03-20",
                    status: "approved",
                    email: "dimas.prasetyo@student.edu",
                    kelas: "10",
                    urgency: "normal",
                },
                {
                    id: 12,
                    siswa: "Ayu Kartika",
                    kegiatan: "Klub Bahasa Inggris",
                    tanggal: "2024-03-21",
                    status: "pending",
                    email: "ayu.kartika@student.edu",
                    kelas: "12",
                    urgency: "normal",
                },
                {
                    id: 13,
                    siswa: "Rizky Ramadhan",
                    kegiatan: "Klub Matematika",
                    tanggal: "2024-03-22",
                    status: "rejected",
                    email: "rizky.ramadhan@student.edu",
                    kelas: "11",
                    urgency: "low",
                },
                {
                    id: 14,
                    siswa: "Sari Melati",
                    kegiatan: "Klub Tari Tradisional",
                    tanggal: "2024-03-23",
                    status: "approved",
                    email: "sari.melati@student.edu",
                    kelas: "10",
                    urgency: "normal",
                },
                {
                    id: 15,
                    siswa: "Bayu Setiawan",
                    kegiatan: "Klub Jurnalistik",
                    tanggal: "2024-03-24",
                    status: "pending",
                    email: "bayu.setiawan@student.edu",
                    kelas: "12",
                    urgency: "high",
                },
            ],
            announcements: @json($pengumuman),
            mentors: @json($pembina),
            users: [{
                    id: 1,
                    username: "admin",
                    email: "admin@ekstraku.edu",
                    role: "Admin",
                    lastLogin: "2024-03-15 10:30",
                    status: "aktif",
                    loginCount: 1245,
                    permissions: ["all"],
                },
                {
                    id: 2,
                    username: "johnson",
                    email: "johnson@school.edu",
                    role: "Mentor",
                    lastLogin: "2024-03-15 09:15",
                    status: "aktif",
                    loginCount: 523,
                    permissions: ["activities", "students"],
                },
                {
                    id: 3,
                    username: "ahmad.rizki",
                    email: "ahmad.rizki@student.edu",
                    role: "Siswa",
                    lastLogin: "2024-03-15 08:45",
                    status: "aktif",
                    loginCount: 189,
                    permissions: ["profile"],
                },
                {
                    id: 4,
                    username: "anderson",
                    email: "anderson@school.edu",
                    role: "Mentor",
                    lastLogin: "2024-03-14 16:20",
                    status: "aktif",
                    loginCount: 678,
                    permissions: ["activities", "students"],
                },
                {
                    id: 5,
                    username: "siti.nur",
                    email: "siti.nur@student.edu",
                    role: "Siswa",
                    lastLogin: "2024-03-14 14:30",
                    status: "aktif",
                    loginCount: 156,
                    permissions: ["profile"],
                },
                {
                    id: 6,
                    username: "dr.smith",
                    email: "smith@school.edu",
                    role: "Mentor",
                    lastLogin: "2024-03-14 11:45",
                    status: "aktif",
                    loginCount: 789,
                    permissions: ["activities", "students"],
                },
                {
                    id: 7,
                    username: "budi.santoso",
                    email: "budi.santoso@student.edu",
                    role: "Siswa",
                    lastLogin: "2024-03-13 15:20",
                    status: "aktif",
                    loginCount: 234,
                    permissions: ["profile"],
                },
                {
                    id: 8,
                    username: "wilson",
                    email: "wilson@school.edu",
                    role: "Mentor",
                    lastLogin: "2024-03-13 13:10",
                    status: "aktif",
                    loginCount: 456,
                    permissions: ["activities", "students"],
                },
                {
                    id: 9,
                    username: "maya.sari",
                    email: "maya.sari@student.edu",
                    role: "Siswa",
                    lastLogin: "2024-03-13 09:30",
                    status: "aktif",
                    loginCount: 167,
                    permissions: ["profile"],
                },
                {
                    id: 10,
                    username: "davis",
                    email: "davis@school.edu",
                    role: "Mentor",
                    lastLogin: "2024-03-12 17:45",
                    status: "aktif",
                    loginCount: 612,
                    permissions: ["activities", "students"],
                },
            ],
            activities_recent: [{
                    icon: "👥",
                    title: "Siswa baru mendaftar",
                    description: "Ahmad Rizki mendaftar ke Klub Basket",
                    time: "10 menit yang lalu",
                    type: "success",
                    category: "registration",
                },
                {
                    icon: "📢",
                    title: "Pengumuman dipublikasi",
                    description: "Pengumuman turnamen basket telah dipublikasi",
                    time: "30 menit yang lalu",
                    type: "info",
                    category: "announcement",
                },
                {
                    icon: "✅",
                    title: "Pendaftaran disetujui",
                    description: "5 pendaftaran baru telah disetujui",
                    time: "1 jam yang lalu",
                    type: "success",
                    category: "approval",
                },
                {
                    icon: "👨‍🏫",
                    title: "Mentor baru ditambahkan",
                    description: "Dr. Tech bergabung sebagai pembina robotika",
                    time: "2 jam yang lalu",
                    type: "warning",
                    category: "mentor",
                },
                {
                    icon: "📊",
                    title: "Laporan bulanan",
                    description: "Laporan partisipasi bulan Maret telah dibuat",
                    time: "3 jam yang lalu",
                    type: "info",
                    category: "report",
                },
                {
                    icon: "🎯",
                    title: "Kegiatan diperbarui",
                    description: "Jadwal Komunitas Drama telah diperbarui",
                    time: "4 jam yang lalu",
                    type: "warning",
                    category: "update",
                },
                {
                    icon: "🔔",
                    title: "Notifikasi sistem",
                    description: "Backup data berhasil dilakukan",
                    time: "5 jam yang lalu",
                    type: "success",
                    category: "system",
                },
                {
                    icon: "📝",
                    title: "Pendaftaran baru",
                    description: "Siti Nurhaliza mendaftar ke Komunitas Drama",
                    time: "6 jam yang lalu",
                    type: "info",
                    category: "registration",
                },
                {
                    icon: "🏆",
                    title: "Prestasi baru",
                    description: "Tim Debat meraih juara 1 tingkat kota",
                    time: "1 hari yang lalu",
                    type: "success",
                    category: "achievement",
                },
                {
                    icon: "📅",
                    title: "Jadwal diperbarui",
                    description: "Jadwal latihan Band Musik diubah",
                    time: "1 hari yang lalu",
                    type: "warning",
                    category: "schedule",
                },
            ],
        };
        console.log(sampleData)
    </script>

    <script src="{{ asset('scripts/admin.js') }}"></script>
</body>

</html>
